### ISSUE TITLE
Character sheet not allowing information to be entered

### ISSUE THREAD

**Issue by Engram24** [piecesofcodecom/household#5]
Per the most recent update on Foundry v. 12.331, categories no longer allow me to enter information; no open text boxes or anything like that
![Screenshot 2024-11-19 235945](https://github.com/user-attachments/assets/9f1848c7-6d8f-4e17-afcd-d92193f72459)

**Comment by Engram24** [comment]
Applicable on all tabs for the character sheet

**Comment by mrcomac** [comment]
Hi,
I didn't understand the issue.

Currently,  you need to create items and drop to the sheet.

In the future release will be available a button to create the items in the sheet.

**Comment by vickyj304** [comment]
NPC corner cards can only be edited through DESCRIPTION. Neither MOVES nor TRAITS can be edited. Thank you for your mod.

English is not my native language, I use GOOGLE Translate
![Uploading 螢幕擷取畫面 2024-11-23 182914.png…]()

**Comment by mrcomac** [comment]
version 2.0.1 has those missing buttons.
